export const Images = {
  authIcon: require("./auth-icon.png"),
  signUp: require("./register.png"),
  back: require("../icons/back.svg"),
  passwordChanged: require("./password-changed.png"),
  fingerprint: require("./fingerprint.png"),
  accountAndCard: require("./account-and-card.png"),
  transfer: require("./transfer.png"),
  withdraw: require("./withdraw.png"),
  prepaid: require("./prepaid.png"),
  bill: require("./bill.png"),
  saveOnline: require("./save-online.png"),
  creditCard: require("./credit-card.png"),
  transactionReport: require("./transaction-report.png"),
  beneficiary: require("./contacts.png"),
  cards: require("./cards.png"),
  visaCard: require("./visa-card.png"),
  masterCard: require("./master-card.png"),
  home: require("../icons/home.svg"),
  message: require("../icons/message.svg"),
  search: require("../icons/search.svg"),
  settings: require("../icons/settings.svg"),
  profilePic: require("./profile-pic.png"),
  notification: require("./notification.png"),
};
